apiVersion: v1
kind: Secret
metadata:
  name: {{ template "single-deployment.fullname" . }}-files
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ toYaml .Values.filesSecret | nindent 2 }}
